/* Recorded narration, generated map.
   ---------------------------------------------------------------------------
   Drop files here and rebuild; nothing else has to change:

       assets/audio/<unitId>/<lang>-<key>.<ext>

   <lang>  en | ur
   <key>   the paragraph's data-para key, i.e. s0 s1 s2 … in story order.
           Keys are the index in unit.story, so one recording serves every age
           tier even though 3-6 sees one paragraph per page and 7-12 sees two.
   <ext>   mp3 | m4a | ogg | opus | webm

   This writes js/data/audio.js:

       window.SS_AUDIO = { jonah: { en: { s0: 'assets/audio/jonah/en-s0.mp3' } } }

   The player prefers a recording and quietly falls back to the device voice for
   any paragraph without one, so a unit can be recorded a paragraph at a time.
   Files are never copied by hand into dist/: build.js ships assets/ whole.     */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const root = path.resolve(import.meta.dirname, '..');
const AUDIO_DIR = path.join(root, 'assets/audio');
const OUT = path.join(root, 'js/data/audio.js');
const EXT = /\.(mp3|m4a|ogg|opus|webm)$/i;
const NAME = /^(en|ur)-([A-Za-z0-9][A-Za-z0-9_-]*)\.[a-z0-9]+$/i;

let units = [];
try {
  for (const f of ['units-1', 'units-2', 'units-3', 'units-4', 'units-5', 'units-6']) {
    const p = path.join(root, 'js/data', f + '.js');
    if (fs.existsSync(p)) units = units.concat(require(p));
  }
} catch (e) { console.log('  (unit data unreadable, skipping checks: ' + e.message + ')'); }
const byId = new Map(units.map((u) => [u.id, u]));

const pack = {};
const problems = [];
const langs = new Set();

if (fs.existsSync(AUDIO_DIR)) {
  for (const unitId of fs.readdirSync(AUDIO_DIR).sort()) {
    const dir = path.join(AUDIO_DIR, unitId);
    if (!fs.statSync(dir).isDirectory()) continue;
    const u = byId.get(unitId);
    if (u) {
      const valid = new Set(u.story.map((_, i) => 's' + i));
      for (const f of ['memory', 'prayer', 'teach']) if (u[f]) valid.add(f);
      for (const file of fs.readdirSync(dir).sort()) {
        const m = file.match(NAME);
        if (!m || !EXT.test(file)) { problems.push(`${unitId}: “${file}” does not match <lang>-<key>.mp3`); continue; }
        const lang = m[1].toLowerCase(), key = m[2];
        if (!valid.has(key)) problems.push(`${unitId}: “${file}” is not a paragraph of this unit (expected ${[...valid].join(', ')})`);
        const bytes = fs.statSync(path.join(dir, file)).size;
        if (bytes < 1024) problems.push(`${unitId}: “${file}” is ${bytes} bytes — looks truncated or empty`);
        langs.add(lang);
        pack[unitId] = pack[unitId] || {};
        pack[unitId][lang] = pack[unitId][lang] || {};
        pack[unitId][lang][key] = `assets/audio/${unitId}/${file}`;
      }
    } else {
      const n = fs.readdirSync(dir).length;
      problems.push(`${unitId}: no such unit, but ${n} recording(s) in assets/audio/${unitId}`);
    }
  }
}

/* sort paragraph keys numerically so the file reads like the story */
for (const id of Object.keys(pack)) for (const lang of Object.keys(pack[id])) {
  const map = pack[id][lang];
  const sorted = {};
  Object.keys(map).sort((a, b) => (parseInt(String(a).slice(1), 10) || 0) - (parseInt(String(b).slice(1), 10) || 0))
    .forEach((k) => { sorted[k] = map[k]; });
  pack[id][lang] = sorted;
}

const clips = Object.values(pack).reduce((n, p) => n + Object.values(p).reduce((k, l) => k + Object.keys(l).length, 0), 0);
const body = JSON.stringify(pack, null, 1).replace(/\n {5}/g, '\n    ');
fs.writeFileSync(OUT, `/* Generated by tools/build-audio.mjs — do not edit by hand.
   Recorded narration for ${Object.keys(pack).length} unit(s), ${clips} clip(s).
   Put files in assets/audio/<unitId>/<lang>-<key>.mp3 and run: npm run audio */
(function (g) {
  g.SS_AUDIO = ${body};
})(typeof window !== 'undefined' ? window : this);
`, 'utf8');

console.log(`audio: ${clips} clip(s) for ${Object.keys(pack).length} unit(s)` +
  (langs.size ? `, language(s): ${[...langs].sort().join(', ')}` : '') + ` → js/data/audio.js`);
if (problems.length) {
  problems.forEach((p) => console.log('  ! ' + p));
  console.log('audio: ' + problems.length + ' problem(s) — the map was still written, but fix these');
  process.exit(1);
}
